- name: Configure all hosts
  hosts: all
  gather_facts: true

- name: Set up HAProxy server
  hosts: HAproxy
  become: true
  gather_facts: true

  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Install HAPROXY
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: "{{ playbook_dir }}/haproxy.cfg.j2"
        dest: /etc/haproxy/haproxy.cfg

    - name: Restart haproxy
      service:
        name: haproxy
        state: restarted

- name: Set up web servers
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: true

  tasks:
    - name: Apt update
      apt:
        update_cache: yes

    - name: Install Python3, pip3, and venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Install Flask
      pip:
        executable: pip3
        name: flask
        state: latest

    - name: Install Gunicorn
      apt:
        name: gunicorn
        state: present

    - name: Copy Application2.py
      copy:
        src: "{{ playbook_dir }}/application2.py"
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Run Flask application using Gunicorn
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 application2:app
      args:
        chdir: /home/ubuntu

- name: Test HAProxy Load Balancing
  hosts: HAproxy
  become: true

  tasks:
    - name: Testing HAproxy - 1st time
      shell: curl localhost
      register: output1
      args:
        warn: false
    - debug: var=output1.stdout

    - name: Testing HAproxy - 2nd time
      shell: curl localhost
      register: output2
      args:
        warn: false
    - debug: var=output2.stdout

    - name: Testing HAproxy - 3rd time
      shell: curl localhost
      register: output3
      args:
        warn: false
    - debug: var=output3.stdout

  
