---
- name: Configure HAProxy and Web Servers
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

- name: Configure HAProxy Server
  hosts: HAproxy
  become: true

  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      notify: Restart HAProxy

    - name: Enable and start HAProxy
      service:
        name: haproxy
        enabled: yes
        state: started

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

- name: Configure Web Servers
  hosts: webservers
  become: true
  gather_facts: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - gunicorn
        state: present
        update_cache: yes

    - name: Install Flask using pip
      pip:
        name: flask
        state: latest
        executable: pip3

    - name: Deploy Flask application
      copy:
        src: application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Run Flask application
      shell: |
        cd /home/ubuntu
        nohup python3 application2.py > /dev/null 2>&1 &
      args:
        executable: /bin/bash
      register: flask_start
      changed_when: "'already in use' not in flask_start.stderr"

    - name: Verify Flask is running
      shell: pgrep -f "python3 application2.py"
      register: flask_running
      ignore_errors: yes

    - name: Debug Flask status
      debug:
        var: flask_running.rc
      
